version: '3.4'

services:
  boss:
    image: ${DOCKER_REGISTRY-}boss
    build:
      context: .
      dockerfile: boss/Dockerfile
    ports:
    - 5000:80
  
  worker:
    depends_on:
    - boss
    image: ${DOCKER_REGISTRY-}worker
    build:
      context: .
      dockerfile: worker/Dockerfile