apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8stest-4704"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8stest-4704"
  template:
    metadata:
      labels:
        app: "k8stest-4704"
    spec:
      containers:
        - name: "k8stest-4704"
          image: "eaterapi.azurecr.io/k8stest"
          ports:
          - containerPort: 80